[package]
name = "dht11"
version = "0.1.0"
authors = ["Jean Paul Stevens"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
thread-priority = "0.2.0"
